<?xml version="1.0"?>
<project
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.openntf.nsfodp.example</groupId>
    <artifactId>single-nsf</artifactId>
	<version>1.0.0-SNAPSHOT</version>
    <packaging>domino-nsf</packaging>

    <pluginRepositories>
        <pluginRepository>
            <id>artifactory.openntf.org</id>
            <name>artifactory.openntf.org</name>
            <url>https://artifactory.openntf.org/openntf</url>
        </pluginRepository>
    </pluginRepositories>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openntf.maven</groupId>
                <artifactId>nsfodp-maven-plugin</artifactId>
                <version>4.1.0-SNAPSHOT</version>
                <extensions>true</extensions>
                <configuration>
					<appendTimestampToTitle>true</appendTimestampToTitle>
					<timestampFormat>yyyy-MM-dd h:mm a zzzz</timestampFormat>
					<templateName>Example Template</templateName>
					<setProductionXspOptions>true</setProductionXspOptions>
                	<acl>
                		<entries>
                			<aclEntry>
                				<name>-Default-</name>
                				<level>manager</level>
                				<defaultEntry>true</defaultEntry>
                				<deleteDocs>true</deleteDocs>
                			</aclEntry>
                			<aclEntry>
                				<name>Anonymous</name>
                				<level>noaccess</level>
                				<type>person</type>
                			</aclEntry>
                			<aclEntry>
                				<name>LocalDomainAdmins</name>
                				<level>manager</level>
                				<type>mixedgroup</type>
                				<deleteDocs>true</deleteDocs>
                			</aclEntry>
                			<aclEntry>
                				<name>LocalDomainServers</name>
                				<level>manager</level>
                				<type>servergroup</type>
                				<deleteDocs>true</deleteDocs>
                			</aclEntry>
                			<aclEntry>
                				<name>OtherDomainServers</name>
                				<level>noaccess</level>
                				<type>servergroup</type>
                				<noReplicate>true</noReplicate>
                			</aclEntry>
                		</entries>
                	</acl>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
